### ISSUE TITLE
The PointConnection does not display properly

### ISSUE THREAD

**Issue by RicardoRepo** [Pana-g/flutter_earth_globe#11]
Hey,guy, I noticed an anomaly while pulling the repo for testing.

It appears in Pana - g/flutter_earth_globe/example/lib/main dart 418 lines of code: _controller. AddPointConnection (e, animateDraw: true); ,
When I change animateDraw: true to animateDraw: false, The PointConnection does not display properly
I guess,You should also be able to reproduce it with this modification

This is my running environment:
Windows 11 PC
Android Studio Giraffe | 2022.3.1 Patch 1
Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (3 weeks ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2
Google Chrome 127.0.6533.120

![屏幕截图 2024-08-20 105645](https://github.com/user-attachments/assets/da471825-48ed-4d0e-ac20-4b7631777865)

**Comment by Pana-g** [comment]
@RicardoRepo This has been fixed in the latest version 1.0.5.
