### ISSUE TITLE
Add surfaces

### ISSUE THREAD

**Issue by Dionjazz** [Pana-g/flutter_earth_globe#2]
Are there any plans to introduce the ability to add image surfaces from the network?

**Comment by Pana-g** [comment]
You can already do that. In the example folder you will see that I'm initializing FlutterEarthGlobeController like this
```dart
_controller = FlutterEarthGlobeController(
        rotationSpeed: 0.05,
        isBackgroundFollowingSphereRotation: true,
        background: Image.asset('assets/2k_stars.jpg').image,
        surface: Image.asset('assets/2k_earth-day.jpg').image);
```
You could use instead:
```dart
_controller = FlutterEarthGlobeController(
        rotationSpeed: 0.05,
        isBackgroundFollowingSphereRotation: true,
        background: Image.asset('assets/2k_stars.jpg').image,
        surface: Image.network('https://www.solarsystemscope.com/textures/download/2k_mars.jpg').image);
```

**Comment by Dionjazz** [comment]
Thanks for reply! But i meant the ability to add additional surfaces, like a list of layers.

**Comment by Pana-g** [comment]
If I understand correctly you want to have multiple surface layers on top of each other?

**Comment by Dionjazz** [comment]
Yes!

**Comment by Pana-g** [comment]
Unfortunately this feature isn't implemented yet.

**Comment by Pana-g** [comment]
Currently there isn't a target time for this feature. As a faster solution you could always create custom texture images with Photoshop or GIMP and create a multi layered texture image.

**Comment by doug-inno** [comment]
How would one go about implementing such a feature? Very cool project.
