### ISSUE TITLE
Can the display height of PointConnection be flexibly changed

### ISSUE THREAD

**Issue by jiezaichan** [Pana-g/flutter_earth_globe#5]
I noticed that the height of PointConnection is fixed at a certain number, regardless of the distance between two points.
For example, I hope that if the distance between two points is very close, the height should be as low as possible, which would be more intuitive.
If I want to achieve this, then what should I do next? Thank you.
Your project is very helpful, and thank you very much for your efforts
![WechatIMG2704](https://github.com/Pana-g/flutter_earth_globe/assets/4098918/1e5d9242-abd6-4960-a5d6-b6de39e57754)

**Comment by Pana-g** [comment]
Thanks for your feedback @jiezaichan ! Unfortunately at this moment there is no way to do this. The height of the mid point for a certain connection is automatically calculated. I may add a way to change this as you suggested in the next release.

**Comment by Pana-g** [comment]
@jiezaichan In the latest version 1.0.4 you can control the `curveScale` of a `PointConnection`

**Comment by jiezaichan** [comment]
Woo~You made it so quickly！
I have a try And it was worked! you're such an amazing guy！
Hope you have happiness every day~
